### ISSUE TITLE
License plate search doesn't quite work on mobile devices like iPad

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#1011]
### What version of Node.js are you using?

v16.13.1

### What version of npm are you using?

8.5.2

### What operating system are you using?

Linux Debian 10

### What version of SnailyCAD are you currently using?

1.18.4 (2022-08-01) newest main branch

### Describe the Bug

For example, if I am on an iPad under: "Officer -> Dashboard -> Plate Search" and then enter e.g. the first letters of a license plate and this is suggested to me and I press on the suggested result the keyboard closes and the suggested result is not executed and also not inserted into the search field.

### Expected Behavior

That you can press on the proposed result as on the PC and then the information opens.

**Comment by Justin2211** [comment]
The same problem also occurs when I want to create a vehicle and enter the model, for example.

**Comment by Dev-CasperTheGhost** [comment]
I'm unable to reproduce this, what phone are you using with what browser? without this information I cannot do much further.

**Comment by Justin2211** [comment]
Hi, I use an iPad with Safari.

**Comment by Justin2211** [comment]
I could make a video

**Comment by Dev-CasperTheGhost** [comment]
yeah sure

**Comment by Dev-CasperTheGhost** [comment]
Fixed now actually.

**Comment by Justin2211** [comment]
Unfortunately it still doesn't work after an update, how did you try it?

**Comment by Dev-CasperTheGhost** [comment]
With an ipad, make sure to rebuild the client.

**Comment by Justin2211** [comment]
What do you mean by "rebuild the client"?
I have updated the CAD using the manual method.

**Comment by Justin2211** [comment]
I have rebuilt the client but no change is visible, so I still can't click on the suggestions

**Comment by Justin2211** [comment]
Ah I found out it works with e.g. Edge on iPad but not in Safari
