### ISSUE TITLE
Bug: Penal Code Groups Missing

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1359]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.41.0 d6f2b0c

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/209736731-7948b795-6672-4846-b800-2434e4e6d023.png)

### Expected Behavior

Groups are not displayed in penal code drop down.

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed? Wasn't able to test locally. Keep me posted @Legacy-TacticalGamingInteractive

**Comment by Legacy-TacticalGamingInteractive** [comment]
> Should be fixed? Wasn't able to test locally. Keep me posted @Legacy-TacticalGamingInteractive


![image](https://user-images.githubusercontent.com/25211271/209883029-433161f3-9841-42d9-95f1-2116b13c8e12.png)


Not fixed yet :(

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now actually :)
