### ISSUE TITLE
[BUG] Failed to load added-to-call.mp3

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#659]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.0.0-beta.89

### Describe the Bug

I added sounds according to the manual along the path /SnailyCADv4/packages/client/public/sounds
Rebuilt the project with the command 'yarn workspace @snailycad/client build'
Start CAD, but I got error in console: GET https://cad.example.com/sounds/incoming-call.mp3 404 (Not Found)
![image](https://user-images.githubusercontent.com/4976837/164994314-23a6732e-86cf-45e3-ae9c-4cc3b05b378f.png)

File status-update.mp3 available.

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
The names you provided are correct. Make sure to also restart the CAD, not only rebuild. That should fix the issue.

**Comment by pp2amd6** [comment]
I rebuild project again, restart the CAD but error still exists

**Comment by Dev-CasperTheGhost** [comment]
Hmm, will need to take a look later today then.

**Comment by Dev-CasperTheGhost** [comment]
Are you able to share your sounds folder, please?

**Comment by pp2amd6** [comment]
You ask about archive with sounds or direct link to CAD sound folder?

**Comment by Dev-CasperTheGhost** [comment]
An image of your folder with your sounds

**Comment by pp2amd6** [comment]
[sounds.zip](https://github.com/SnailyCAD/snaily-cadv4/files/8554209/sounds.zip)

**Comment by Dev-CasperTheGhost** [comment]
Weird. All the names are correct. I’m confused lol, will take a greater look when I’m home from school

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost you can close bug. My fault, I use double file extension (added-to-call.**mp3.mp3**). Sorry 😞

**Comment by Dev-CasperTheGhost** [comment]
Ah no worries!
